pacrefs/force-app/main/default/objects/MetaDataUpload__c/MetaDataUpload__c.object-meta.xml
<CustomObject>
    <label>MetaDataUpload</label>
    <nameField>
        <displayFormat>MDU-{0000000}</displayFormat>
        <label>MetaDataUpload Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MetaDataUploads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

pacrefs/force-app/main/default/objects/MetaDataUpload__c/fields/buildArtifact__c.field-meta.xml
<CustomField>
    <fullName>buildArtifact__c</fullName>
    <description>This is the customer's artifact that is calling the managed package component</description>
    <inlineHelpText>This is the customer's artifact that is calling the managed package component</inlineHelpText>
    <label>buildArtifact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

pacrefs/force-app/main/default/objects/MetaDataUpload__c/fields/category__c.field-meta.xml
<CustomField>
    <fullName>category__c</fullName>
    <label>category</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

pacrefs/force-app/main/default/SetFunctionalArea.cls
global class SetFunctionalArea implements Database.Batchable<sObject>
{

    public String version;

    public Map<String,String> configureMap = MetadataParser.populateFunctionalMap();   

	global Database.QueryLocator start(Database.BatchableContext BC)
	{
        String query = 'SELECT Id,buildArtifact__c FROM MetaDataUpload__c';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<MetaDataUpload__c> scope)
    {
        for ( MetaDataUpload__c mdu : scope)
        {
            mdu.category__c = configureMap.get(mdu.BuildArtifact__c);
        }
        update scope;
    }  

    global void finish(Database.BatchableContext BC)
    {
    }
}