pacrefs/force-app/main/default/objects/MetaDataUpload__c/MetaDataUpload__c.object-meta.xml
<CustomObject>
    <label>MetaDataUpload</label>
    <nameField>
        <displayFormat>MDU-{0000000}</displayFormat>
        <label>MetaDataUpload Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MetaDataUploads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

pacrefs/force-app/main/default/objects/MetaDataUpload__c/fields/buildArtifact__c.field-meta.xml
<CustomField>
    <fullName>buildArtifact__c</fullName>
    <description>This is the customer's artifact that is calling the managed package component</description>
    <inlineHelpText>This is the customer's artifact that is calling the managed package component</inlineHelpText>
    <label>buildArtifact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

pacrefs/force-app/main/default/objects/MetaDataUpload__c/fields/buildVersion__c.field-meta.xml
<CustomField>
    <fullName>buildVersion__c</fullName>
    <description>version of the package build</description>
    <label>buildVersion</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

pacrefs/force-app/main/default/objects/MetaDataUpload__c/fields/CommonBuildArtifact__c.field-meta.xml
<CustomField>
    <fullName>CommonBuildArtifact__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this artifact common to old and new builds</description>
    <inlineHelpText>Is this artifact common to old and new builds</inlineHelpText>
    <label>CommonBuildArtifact</label>
    <type>Checkbox</type>
</CustomField>

pacrefs/force-app/main/default/objects/MetaDataUpload__c/fields/Ignore_In_Reports__c.field-meta.xml
<CustomField>
    <fullName>Ignore_In_Reports__c</fullName>
    <defaultValue>false</defaultValue>
    <description>checked if the field should be ignored in some reports, for example text class references or indeterminate items</description>
    <inlineHelpText>checked if the field should be ignored in some reports, for example text class references or indeterminate items</inlineHelpText>
    <label>Ignore In Reports</label>
    <type>Checkbox</type>
</CustomField>

pacrefs/force-app/main/default/objects/MetaDataUpload__c/fields/metadataType__c.field-meta.xml
<CustomField>
    <fullName>metadataType__c</fullName>
    <label>metadataType</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

pacrefs/force-app/main/MatchCommonArtifacts.cls
global class MatchCommonArtifacts implements Database.Batchable<sObject>
{

	global Database.QueryLocator start(Database.BatchableContext BC)
	{
        Set<String> buildArtifactsV3 = new Set<String>();
        Set<String> buildArtifactsV4 = new Set<String>();

        AggregateResult[] arBuildArtifactsV3
          = [SELECT buildArtifact__c from MetaDataUpload__c where buildVersion__c = 'V3' and Ignore_In_Reports__c = false and metadatatype__c ='md' group by buildArtifact__c LIMIT 49999];
        AggregateResult[] arBuildArtifactsV4
          = [SELECT buildArtifact__c from MetaDataUpload__c where buildVersion__c = 'V4' and Ignore_In_Reports__c = false and metadatatype__c ='md'  group by buildArtifact__c LIMIT 49999];

        for (AggregateResult ar : arBuildArtifactsV3)  {
            buildArtifactsV3.add((String) ar.get('buildArtifact__c'));
        }        
        for (AggregateResult ar : arBuildArtifactsV4)  {
            buildArtifactsV4.add((String) ar.get('buildArtifact__c'));
        }        

        String query = 'SELECT Id,CommonBuildArtifact__c FROM MetaDataUpload__c where buildArtifact__c IN :buildArtifactsV3 and buildArtifact__c IN :buildArtifactsV4' ;
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<MetaDataUpload__c> scope)
    {
        for ( MetaDataUpload__c mdu : scope)
        {
            mdu.CommonBuildArtifact__c = true;
        }
        update scope;
    }  

    global void finish(Database.BatchableContext BC)
    {
    }
}