pacrefs/force-app/main/default/objects/MetaDataUpload__c/MetaDataUpload__c.object-meta.xml
<CustomObject>
    <label>MetaDataUpload</label>
    <nameField>
        <displayFormat>MDU-{0000000}</displayFormat>
        <label>MetaDataUpload Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MetaDataUploads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

pacrefs/force-app/main/default/objects/MetaDataUpload__c/fields/buildArtifact__c.field-meta.xml
<CustomField>
    <fullName>buildArtifact__c</fullName>
    <description>This is the customer's artifact that is calling the managed package component</description>
    <inlineHelpText>This is the customer's artifact that is calling the managed package component</inlineHelpText>
    <label>buildArtifact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

pacrefs/force-app/main/default/objects/MetaDataUpload__c/fields/Ignore_In_Reports__c.field-meta.xml
<CustomField>
    <fullName>Ignore_In_Reports__c</fullName>
    <defaultValue>false</defaultValue>
    <description>checked if the field should be ignored in some reports, for example text class references or indeterminate items</description>
    <inlineHelpText>checked if the field should be ignored in some reports, for example text class references or indeterminate items</inlineHelpText>
    <label>Ignore In Reports</label>
    <type>Checkbox</type>
</CustomField>

pacrefs/force-app/main/default/objects/MetaDataUpload__c/fields/metadataType__c.field-meta.xml
<CustomField>
    <fullName>metadataType__c</fullName>
    <label>metadataType</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

pacrefs/force-app/main/default/objects/MetaDataUpload__c/fields/packageComponent__c.field-meta.xml
<CustomField>
    <fullName>packageComponent__c</fullName>
    <description>The component in the managed package being referenced</description>
    <inlineHelpText>The component in the managed package being referenced</inlineHelpText>
    <label>packageComponent</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

pacrefs/force-app/main/default/objects/MetaDataUpload__c/fields/packageComponentParent__c.field-meta.xml
<CustomField>
    <fullName>packageComponentParent__c</fullName>
    <description>The parent component in the package being referenced (e.g. the object that a referenced field is associated with). This will often be empty</description>
    <inlineHelpText>The parent component in the package being referenced (e.g. the object that a referenced field is associated with). This will often be empty</inlineHelpText>
    <label>packageComponentParent</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

pacrefs/force-app/main/default/objects/MetaDataUpload__c/fields/rawText__c.field-meta.xml
<CustomField>
    <fullName>rawText__c</fullName>
    <description>Text that appears in the metadata file</description>
    <inlineHelpText>Text that appears in the metadata file</inlineHelpText>
    <label>rawText</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

pacrefs/force-app/main/default/MetadataParser_Test.cls
@IsTest
public with sharing class MetadataParser_Test {

    @IsTest public static void parseSingleField ()
    {
        String REPORT_TYPE_SAMPLE = './reportTypes/Account_with_Applications.reportType:            <field>Agency__c.ACCL__Geolocation__Latitude__s</field>';
        MetadataParser mdp = new MetadataParser();
        MetaDataUpload__c mdu = mdp.parse(REPORT_TYPE_SAMPLE)[0];
        System.assertEquals('            <field>Agency__c.ACCL__Geolocation__Latitude__s</field>',mdu.rawText__c);

        System.assertEquals('reportType',mdu.metadataType__c);
        System.assertEquals('Account_with_Applications',mdu.buildArtifact__c);
        System.assertEquals('Agency__c',mdu.packageComponentParent__c);
        System.assertEquals('ACCL__Geolocation__Latitude__s',mdu.packageComponent__c);
        System.assert(!mdu.ignore_in_reports__c);

    }

    @IsTest public static void parseMultiple ()
    {
        String REPORT_TYPE_SAMPLE = './pages/TPM_CreatePromotion.page:                    <apex:outputLabel value="{!$ObjectType.ACCL__Promotion__c.Fields.ACCL__Promotion_Template__c.Label}"';

        MetadataParser mdp = new MetadataParser();
        MetaDataUpload__c mdu = mdp.parse(REPORT_TYPE_SAMPLE)[0];
        System.assertEquals('page',mdu.metadataType__c);
        System.assertEquals('TPM_CreatePromotion',mdu.buildArtifact__c);
        System.assertEquals('ACCL__Promotion__c',mdu.packageComponent__c);

        mdu = mdp.parse(REPORT_TYPE_SAMPLE)[1];
        System.assertEquals('page',mdu.metadataType__c);
        System.assertEquals('TPM_CreatePromotion',mdu.buildArtifact__c);
        System.assertEquals('ACCL__Promotion_Template__c',mdu.packageComponent__c);
    }

    @IsTest public static void splitByPrefix ()
    {
        String s = '<apex:outputLabel value="{!$ObjectType.ACCL__Promotion__c.Fields.ACCL__Promotion_Template__c.Label}"';
        List<String> split = MetadataParser.splitByPrefix(s, 'ACCL');
        System.assertEquals('ACCL__Promotion__c.Fields.', split[0]);
        System.assertEquals('ACCL__Promotion_Template__c.Label}"', split[1]);
    }

    @IsTest public static void stripToReference ()
    {
        String s = 'ACCL__Promotion_Template__cxyz"';
        String terminator = '__c';
        String stripped = MetadataParser.stripToReference(s, terminator);
        System.assertEquals('ACCL__Promotion_Template__c', stripped);
    }

    @IsTest public static void stripToFirstReference ()
    {
        String s = 'ACCL__Promotion_Template__cxyz"';
        String[] terminators = new String[] {'__c','zumba'};
        String stripped = MetadataParser.stripToFirstReference(s, terminators);
        System.assertEquals('ACCL__Promotion_Template__c', stripped);
    }

    @IsTest public static void ignore ()
    {
        String REPORT_TYPE_SAMPLE = './classes/TPM_MyPromotionRomoteActionExt_2_Test.cls:            ACCL__Product__c productid2 = TPM_Testdatafactory.createProduct(prodtemp);';
        MetadataParser mdp = new MetadataParser();
        MetaDataUpload__c mdu = mdp.parse(REPORT_TYPE_SAMPLE)[0];

        System.assert(mdu.ignore_in_reports__c);
    }


    

}