pacrefs/force-app/main/default/objects/GrepLine__c/GrepLine__c.object-meta.xml
<CustomObject>
    <label>GrepLine</label>
    <nameField>
        <displayFormat>GL-{0000000}</displayFormat>
        <label>GrepLine Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GrepLines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

pacrefs/force-app/main/default/objects/GrepLine__c/fields/fileLine__c.field-meta.xml
<CustomField>
    <fullName>fileLine__c</fullName>
    <description>Line from the grep file</description>
    <label>fileLine</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

pacrefs/force-app/main/default/objects/MetaDataUpload__c/MetaDataUpload__c.object-meta.xml
<CustomObject>
    <label>MetaDataUpload</label>
    <nameField>
        <displayFormat>MDU-{0000000}</displayFormat>
        <label>MetaDataUpload Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MetaDataUploads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

pacrefs/force-app/main/default/objects/MetaDataUpload__c/fields/buildVersion__c.field-meta.xml
<CustomField>
    <fullName>buildVersion__c</fullName>
    <description>version of the package build</description>
    <label>buildVersion</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

pacrefs/force-app/main/default/objects/MetaDataUpload__c/fields/fileLine__c.field-meta.xml
<CustomField>
    <fullName>fileLine__c</fullName>
    <label>fileLine</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

pacrefs/force-app/main/default/ProcessAnalysisRecords.cls
global class ProcessAnalysisRecords implements Database.Batchable<sObject>
{

    public String version;

	global Database.QueryLocator start(Database.BatchableContext BC)
	{
        String query = 'SELECT Id,fileLine__c FROM GrepLine__c ';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<GrepLine__c> scope)
    {
        List<MetaDataUpload__c> listmdu = new List<MetaDataUpload__c>();
        
        MetadataParser mdp = new MetadataParser();

        for ( GrepLine__c gl : scope)
        {
            listmdu.addAll(mdp.parse(gl.fileLine__c));
        }
        for ( MetaDataUpload__c mdu : listmdu)
        {
            mdu.buildVersion__c = version;
        }
        insert listmdu;
    }  

    global void finish(Database.BatchableContext BC)
    {
    }
}