pacrefs/force-app/main/default/objects/GrepLine__c/GrepLine__c.object-meta.xml
<CustomObject>
    <label>GrepLine</label>
    <nameField>
        <displayFormat>GL-{0000000}</displayFormat>
        <label>GrepLine Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GrepLines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

pacrefs/force-app/main/default/objects/GrepLine__c/fields/fileLine__c.field-meta.xml
<CustomField>
    <fullName>fileLine__c</fullName>
    <description>Line from the grep file</description>
    <label>fileLine</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

pacrefs/force-app/main/default/objects/MetaDataJobRunner__c/MetaDataJobRunner__c.object-meta.xml
<CustomObject>
    <label>MetaDataJobRunner</label>
    <nameField>
        <label>MetaDataJobRunner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MetaDataJobRunners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

pacrefs/force-app/main/default/objects/MetaDataJobRunner__c/fields/JobName__c.field-meta.xml
<CustomField>
    <fullName>JobName__c</fullName>
    <label>JobName</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>V3Process</fullName>
            </value>
            <value>
                <fullName>V4Process</fullName>
            </value>
            <value>
                <fullName>ClearMetaDataUploads</fullName>
            </value>
            <value>
                <fullName>ClearStaging</fullName>
            </value>
            <value>
                <fullName>SetFunctionalArea</fullName>
            </value>
            <value>
                <fullName>MatchCommonArtifacts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

pacrefs/force-app/main/default/objects/MetaDataUpload__c/MetaDataUpload__c.object-meta.xml
<CustomObject>
    <label>MetaDataUpload</label>
    <nameField>
        <displayFormat>MDU-{0000000}</displayFormat>
        <label>MetaDataUpload Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MetaDataUploads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

pacrefs/force-app/main/default/objects/MetaDataUpload__c/fields/fileLine__c.field-meta.xml
<CustomField>
    <fullName>fileLine__c</fullName>
    <label>fileLine</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

pacrefs/force-app/main/default/Batchables_Test.cls
@isTest 
public class Batchables_Test 
{
    @IsTest static void testSetFunctionalArea() 
    {
        String REPORT_TYPE_SAMPLE = './pages/TPM_CreatePromotion.page:                    <apex:outputLabel value="{!$ObjectType.ACCL__Promotion__c.Fields.ACCL__Promotion_Template__c.Label}"';
        List<MetaDataUpload__c> listmdu = new List<MetaDataUpload__c>();

        MetadataParser mdp = new MetadataParser();
        MetaDataUpload__c mdu = mdp.parse(REPORT_TYPE_SAMPLE)[0];
        listmdu.add(mdu);
        
        insert listmdu;
        
        Test.startTest();
        SetFunctionalArea obj = new SetFunctionalArea();
        DataBase.executeBatch(obj); 
        Test.stopTest();
    }

    @IsTest static void testDeleteAnalysisRecords() 
    {
        String REPORT_TYPE_SAMPLE = './pages/TPM_CreatePromotion.page:                    <apex:outputLabel value="{!$ObjectType.ACCL__Promotion__c.Fields.ACCL__Promotion_Template__c.Label}"';
        List<MetaDataUpload__c> listmdu = new List<MetaDataUpload__c>();

        MetadataParser mdp = new MetadataParser();
        MetaDataUpload__c mdu = mdp.parse(REPORT_TYPE_SAMPLE)[0];
        listmdu.add(mdu);
        
        insert listmdu;
        
        Test.startTest();
        DeleteAnalysisRecords obj = new DeleteAnalysisRecords();
        obj.query = 'select id from MetaDataUpload__c';
        DataBase.executeBatch(obj); 
        Test.stopTest();
    }

    @IsTest static void testMatchCommonArtifacts() 
    {
        String REPORT_TYPE_SAMPLE = './pages/TPM_CreatePromotion.page:                    <apex:outputLabel value="{!$ObjectType.ACCL__Promotion__c.Fields.ACCL__Promotion_Template__c.Label}"';
        List<MetaDataUpload__c> listmdu = new List<MetaDataUpload__c>();

        MetadataParser mdp = new MetadataParser();
        MetaDataUpload__c mdu = mdp.parse(REPORT_TYPE_SAMPLE)[0];
        listmdu.add(mdu);
        
        insert listmdu;
        
        Test.startTest();
        MatchCommonArtifacts obj = new MatchCommonArtifacts();
        DataBase.executeBatch(obj); 
        Test.stopTest();
    }

    @IsTest static void testProcessAnalysisRecords() 
    {
        String REPORT_TYPE_SAMPLE = './pages/TPM_CreatePromotion.page:                    <apex:outputLabel value="{!$ObjectType.ACCL__Promotion__c.Fields.ACCL__Promotion_Template__c.Label}"';
        List<GrepLine__c> lines = new List<GrepLine__c>();
        GrepLine__c gl = new GrepLine__c(fileLine__c = REPORT_TYPE_SAMPLE);
        insert lines;
        
        Test.startTest();
        ProcessAnalysisRecords obj = new ProcessAnalysisRecords();
        DataBase.executeBatch(obj); 
        Test.stopTest();
    }

    @IsTest static void testSetFunctionalAreaTrigger() 
    {
        String REPORT_TYPE_SAMPLE = './pages/TPM_CreatePromotion.page:                    <apex:outputLabel value="{!$ObjectType.ACCL__Promotion__c.Fields.ACCL__Promotion_Template__c.Label}"';
        List<MetaDataUpload__c> listmdu = new List<MetaDataUpload__c>();
        MetadataParser mdp = new MetadataParser();
        MetaDataUpload__c mdu = mdp.parse(REPORT_TYPE_SAMPLE)[0];
        listmdu.add(mdu);
        
        insert listmdu;
        
        Test.startTest();
        MetaDataJobRunner__c mdjr = new MetaDataJobRunner__c(JobName__c = 'SetFunctionalArea');
        insert mdjr;
        Test.stopTest();
    }

    @IsTest static void testDeleteAnalysisRecordsTrigger() 
    {
        String REPORT_TYPE_SAMPLE = './pages/TPM_CreatePromotion.page:                    <apex:outputLabel value="{!$ObjectType.ACCL__Promotion__c.Fields.ACCL__Promotion_Template__c.Label}"';
        List<MetaDataUpload__c> listmdu = new List<MetaDataUpload__c>();

        MetadataParser mdp = new MetadataParser();
        MetaDataUpload__c mdu = mdp.parse(REPORT_TYPE_SAMPLE)[0];
        listmdu.add(mdu);
        
        insert listmdu;
        
        Test.startTest();
        MetaDataJobRunner__c mdjr = new MetaDataJobRunner__c(JobName__c = 'ClearMetaDataUploads');
        insert mdjr;
        Test.stopTest();
    }

    @IsTest static void testDeleteAnalysisRecordsTriggerStaging() 
    {
        String REPORT_TYPE_SAMPLE = './pages/TPM_CreatePromotion.page:                    <apex:outputLabel value="{!$ObjectType.ACCL__Promotion__c.Fields.ACCL__Promotion_Template__c.Label}"';
        List<MetaDataUpload__c> listmdu = new List<MetaDataUpload__c>();

        MetadataParser mdp = new MetadataParser();
        MetaDataUpload__c mdu = mdp.parse(REPORT_TYPE_SAMPLE)[0];
        listmdu.add(mdu);
        
        insert listmdu;
        
        Test.startTest();
        MetaDataJobRunner__c mdjr = new MetaDataJobRunner__c(JobName__c = 'ClearStaging');
        insert mdjr;
        Test.stopTest();
    }

    @IsTest static void testMatchCommonArtifactsTrigger() 
    {
        String REPORT_TYPE_SAMPLE = './pages/TPM_CreatePromotion.page:                    <apex:outputLabel value="{!$ObjectType.ACCL__Promotion__c.Fields.ACCL__Promotion_Template__c.Label}"';
        List<MetaDataUpload__c> listmdu = new List<MetaDataUpload__c>();

        MetadataParser mdp = new MetadataParser();
        MetaDataUpload__c mdu = mdp.parse(REPORT_TYPE_SAMPLE)[0];
        listmdu.add(mdu);
        
        insert listmdu;
        
        Test.startTest();
        MetaDataJobRunner__c mdjr = new MetaDataJobRunner__c(JobName__c = 'MatchCommonArtifacts');
        insert mdjr;
        Test.stopTest();
    }

    @IsTest static void testProcessAnalysisRecordsTriggerV3() 
    {
        String REPORT_TYPE_SAMPLE = './pages/TPM_CreatePromotion.page:                    <apex:outputLabel value="{!$ObjectType.ACCL__Promotion__c.Fields.ACCL__Promotion_Template__c.Label}"';
        List<GrepLine__c> lines = new List<GrepLine__c>();
        GrepLine__c gl = new GrepLine__c(fileLine__c = REPORT_TYPE_SAMPLE);
        insert lines;
        
        Test.startTest();
        MetaDataJobRunner__c mdjr = new MetaDataJobRunner__c(JobName__c = 'V3Process');
        insert mdjr;
        Test.stopTest();
    }

    @IsTest static void testProcessAnalysisRecordsTriggerV4() 
    {
        String REPORT_TYPE_SAMPLE = './pages/TPM_CreatePromotion.page:                    <apex:outputLabel value="{!$ObjectType.ACCL__Promotion__c.Fields.ACCL__Promotion_Template__c.Label}"';
        List<GrepLine__c> lines = new List<GrepLine__c>();
        GrepLine__c gl = new GrepLine__c(fileLine__c = REPORT_TYPE_SAMPLE);
        insert lines;
        
        Test.startTest();
        MetaDataJobRunner__c mdjr = new MetaDataJobRunner__c(JobName__c = 'V4Process');
        insert mdjr;
        Test.stopTest();
    }


}